Repository IgniteUI/igniteui-docfx-template, pull requests merged in 2018-05, with the labels that each got.

#2 add package.json and ci npm deploy config
  .travis.yml
  package.json
Labels: npm

#5 set iframe body overflow
  styles/sample-iframe-handler.js
Labels: bug, status: verified

#6 remove setting overflow: hideen to the iframe body
  styles/sample-iframe-handler.js
Labels: status: verified
