Repository IgniteUI/igniteui-docfx-template, pull requests merged in 2018-09, with the labels that each got.

#38 Update readme.md with npm version badge
  README.md
Labels: npm, status: verified

#40 Fixed StackBlitz not opening
  styles/stackblitz-handler.js
Labels: status: verified

#44 add url for sass docs
  post-processors/PostProcessors/EnvironmentVariables/preconfig.json
Labels: status: in-test
