Repository IgniteUI/igniteui-docfx-template, pull requests merged in 2018-07, with the labels that each got.

#18 build(npm): update npm deploy token
  .travis.yml
Labels: npm, status: verified

#19 Added new template elements to allow for theming and added indigo styles
  layout/_master.tmpl
  partials/li.tmpl.partial
  styles/css/main.css
  styles/sass/_variables.scss
  styles/sass/partials/_navbar.scss
Labels: status: awaiting-test

#24 Updated the Infragistics header & footer
  layout/_master.tmpl
  partials/infrafoot.ja.tmpl.partial
  partials/infrafoot.tmpl.partial
  partials/infranav.ja.tmpl.partial
  partials/infranav.tmpl.partial
  post-processors/PostProcessors/EnvironmentVariables/preconfig.json
  styles/api-browser.js
Labels: status: verified
