Repository IgniteUI/igniteui-docfx-template, pull requests merged in 2018-08, with the labels that each got.

#30 Added environment specific GTM container ids.
  layout/_master.tmpl
  partials/footer.tmpl.partial
  partials/head.tmpl.partial
  post-processors/PostProcessors/EnvironmentVariables/preconfig.json
Labels: status: verified

#31 updating the design
  styles/css/main.css
  styles/docfx.js
  styles/sass/_variables.scss
  styles/sass/partials/_affix.scss
  styles/sass/partials/_alerts.scss
  styles/sass/partials/_anchorjs.scss
  styles/sass/partials/_button-link.scss
  styles/sass/partials/_hljs.scss
  styles/sass/partials/_igx-typography.scss
  styles/sass/partials/_table.scss
  styles/sass/partials/_toc.scss
  styles/sass/partials/_typography.scss
  toc.extension.js
Labels: status: awaiting-test

#32 feat(toc): enable TOC item filtering
  partials/li.tmpl.partial
  styles/css/main.css
  styles/docfx.js
  styles/sass/partials/_toc.scss
  toc.extension.js
  toc.html.tmpl
Labels: enhancement, status: verified

#37 keep the stackblitz button disabled until necessary resources are loaded
  styles/stackblitz-handler.js
Labels: status: verified
