Repository IgniteUI/igniteui-docfx-template, pull requests merged in 2018-06, with the labels that each got.

#8 Dynamic navbar title
  partials/logo.tmpl.partial
  styles/css/main.css
  styles/sass/partials/_navbar.scss
Labels: status: awaiting-test

#11 feat(toc): allow sidenav headers to be linkable
  package-lock.json
  partials/li.tmpl.partial
  styles/css/main.css
  styles/docfx.js
  styles/sass/partials/_toc.scss
Labels: enhancement, status: verified

#12 feat: added mktg feature styles and lazyload script
  partials/scripts.tmpl.partial
  styles/css/main.css
  styles/lazyload.js
  styles/sass/main.scss
  styles/sass/partials/_button-link.scss
  styles/sass/partials/_features.scss
Labels: status: awaiting-test, status: in-test

#15 Fixed resources file path
  styles/docfx.js
Labels: status: verified

#16 Fixed resources
  layout/_master.tmpl
  resources/resources-en.json
  resources/resources-ja.json
  styles/docfx.js
Labels: status: verified
