Repository IgniteUI/igniteui-docfx-template, pull requests merged in 2022-09, with the labels that each got.

#385 V dyulgerov/add download now button master
  src/app/services/code-view/common.ts
  src/app/services/rendering/navbar.ts
  src/app/services/router.ts
  src/i18n/constants-en.ts
  src/i18n/constants-jp.ts
  src/styles/shared/components/_infranav.scss
  template/conceptual.html.primary.js
  template/partials/helloBar.tmpl.partial
  template/partials/infranav.ja.tmpl.partial
  template/partials/infranav.tmpl.partial
Labels: status: verified, status: pending-localization

#387 Remove duplicated hello bar
  src/app/services/navigation.ts
  src/app/services/rendering/navbar.ts
  template/partials/helloBar.tmpl.partial
Labels: status: verified

#389 [Localization] Updating Download button localization.
  src/i18n/constants-jp.ts
Labels: status: verified, status: localized

#390 Set different cta banner links based on localized version
  src/app/services/rendering/article.ts
  src/styles/shared/components/_infranav.scss
Labels: status: verified

#392 Fix toc alignment
  src/app/services/rendering/navbar.ts
Labels: status: verified

#393 Improve localization functionality
  package-lock.json
  package.json
  src/app/services/code-view/code-view.ts
  src/app/services/localization.ts
  src/app/services/rendering/navbar.ts
  src/i18n/constants-en.ts
  src/i18n/constants-jp.ts
  src/i18n/resources-en.json
  src/i18n/resources-ja.json
  src/i18n/resources-kr.json
Labels: status: verified
