Repository IgniteUI/igniteui-docfx-template, pull requests merged in 2023-01, with the labels that each got.

#405 Fix note gap
  src/styles/ignite-ui/_variables.scss
Labels: status: verified

#408 Update copyright date
  template/partials/slingshot/slingshotfoot.ja.tmpl.partial
  template/partials/slingshot/slingshotfoot.tmpl.partial
Labels: status: awaiting-test

#410 Add jp frameworks navigation links
  template/partials/frameworks.ja.tmpl.partial
  template/partials/frameworks.tmpl.partial
  template/partials/navbar.tmpl.partial
Labels: status: verified, status: pending-localization

#411 Handle default sample metadata paths
  src/app/services/code-view/angular-code-service.ts
Labels: status: awaiting-test

#412 Fix default module samples cors error
  src/app/services/code-view/angular-code-service.ts
Labels: status: awaiting-test
